INFO:uvicorn.error:Started server process [51143]
INFO:uvicorn.error:Waiting for application startup.
[Wed Jan 19 13:22:25 2022][INFO][main.py][line:15] - starting up
INFO:uvicorn.error:Application startup complete.
[Wed Jan 19 13:22:29 2022][INFO][utils.py][line:353] - client-update
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00076s] ()
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT client.id, client.name, client.`key`, client.active, client.`totalHit` 
FROM client 
WHERE client.id = %s
INFO:sqlalchemy.engine.Engine:[generated in 0.00420s] (1,)
INFO:sqlalchemy.engine.Engine:UPDATE client SET name=%s, `key`=%s WHERE client.id = %s
INFO:sqlalchemy.engine.Engine:[generated in 0.00168s] ('asd', '$2b$12$ab/G5AeUEMUhJA/NsYzwMe.3sf0PxHPYk8jyLNRTwUU4p3LJG3vRG', 1)
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT client.id, client.name, client.`key`, client.active, client.`totalHit` 
FROM client 
WHERE client.id = %s
INFO:sqlalchemy.engine.Engine:[generated in 0.00152s] (1,)
INFO:sqlalchemy.engine.Engine:ROLLBACK
[Wed Jan 19 13:22:35 2022][INFO][utils.py][line:353] - client-read
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT count(*) AS count_1 
FROM (SELECT client.id AS id, client.name AS name, client.`key` AS `key`, client.active AS active, client.`totalHit` AS `totalHit` 
FROM client) AS anon_1
INFO:sqlalchemy.engine.Engine:[generated in 0.00306s] ()
INFO:sqlalchemy.engine.Engine:SELECT client.id, client.name, client.`key`, client.active, client.`totalHit` 
FROM client ORDER BY client.id ASC 
 LIMIT %s, %s
INFO:sqlalchemy.engine.Engine:[generated in 0.00385s] (0, 20)
INFO:sqlalchemy.engine.Engine:ROLLBACK
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
[Wed Jan 19 13:22:53 2022][INFO][main.py][line:19] - shutting down
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [51143]
